apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-journalforing-ferdigstill
spec:
  replicas:
    min: 6
    max: 6
  vault:
    paths:
      - kvPath: "serviceuser/data/prod/srvdagpenger-journ"
        mountPath: "/secrets/serviceuser/srvdp-jrnf-ferdig"
      - kvPath: "kv/prod/fss/dagpenger-journalforing-ferdigstill/default"
        mountPath: "/var/run/secrets/nais.io/vault/"


